import type { Metadata } from "next";
import "./globals.css";
import AppProvider from "@/components/app-provider";
   

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className="light"
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">

        <AppProvider>
          {children}
        </AppProvider>

      </body>
    </html>
  );
}
