/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/chat/conversations/direct": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GetOrCreateConversationRequest"];
                    "text/json": components["schemas"]["GetOrCreateConversationRequest"];
                    "application/*+json": components["schemas"]["GetOrCreateConversationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["HttpResultOfGuid"];
                        "application/json": components["schemas"]["HttpResultOfGuid"];
                        "text/json": components["schemas"]["HttpResultOfGuid"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/conversations/direct/:{receiverId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    receiverId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["HttpResultOfGuid"];
                        "application/json": components["schemas"]["HttpResultOfGuid"];
                        "text/json": components["schemas"]["HttpResultOfGuid"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/conversations/direct/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    ConversationId?: string;
                    BeforeMessageId?: string;
                    PageSize?: number | string;
                    UserId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["HttpResultOfIEnumerableOfChatMessageResponse"];
                        "application/json": components["schemas"]["HttpResultOfIEnumerableOfChatMessageResponse"];
                        "text/json": components["schemas"]["HttpResultOfIEnumerableOfChatMessageResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["HttpResultOfIEnumerableOfUserConversationResponse"];
                        "application/json": components["schemas"]["HttpResultOfIEnumerableOfUserConversationResponse"];
                        "text/json": components["schemas"]["HttpResultOfIEnumerableOfUserConversationResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/conversations/direct/details/:{conversationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    conversationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["HttpResultOfConversationDetailsResponse"];
                        "application/json": components["schemas"]["HttpResultOfConversationDetailsResponse"];
                        "text/json": components["schemas"]["HttpResultOfConversationDetailsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SendMessageRequest"];
                    "text/json": components["schemas"]["SendMessageRequest"];
                    "application/*+json": components["schemas"]["SendMessageRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["HttpResultOfGetUserProfileResponse"];
                        "application/json": components["schemas"]["HttpResultOfGetUserProfileResponse"];
                        "text/json": components["schemas"]["HttpResultOfGetUserProfileResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Username?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["HttpResultOfIEnumerableOfGetUserResponse"];
                        "application/json": components["schemas"]["HttpResultOfIEnumerableOfGetUserResponse"];
                        "text/json": components["schemas"]["HttpResultOfIEnumerableOfGetUserResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterUserRequest"];
                    "text/json": components["schemas"]["RegisterUserRequest"];
                    "application/*+json": components["schemas"]["RegisterUserRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["HttpResult"];
                        "application/json": components["schemas"]["HttpResult"];
                        "text/json": components["schemas"]["HttpResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginUserRequest"];
                    "text/json": components["schemas"]["LoginUserRequest"];
                    "application/*+json": components["schemas"]["LoginUserRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["HttpResult"];
                        "application/json": components["schemas"]["HttpResult"];
                        "text/json": components["schemas"]["HttpResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["HttpResult"];
                        "application/json": components["schemas"]["HttpResult"];
                        "text/json": components["schemas"]["HttpResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["HttpResult"];
                        "application/json": components["schemas"]["HttpResult"];
                        "text/json": components["schemas"]["HttpResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ChatMessageResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            senderId: string;
            /** Format: uuid */
            conversationId: string;
            content: string;
            status: string;
            /** Format: date-time */
            createdAt: string;
        };
        ConversationDetailsResponse: {
            /** Format: uuid */
            userId: string;
            name: string;
        };
        GetOrCreateConversationRequest: {
            /** Format: uuid */
            receiverId: string;
        };
        GetUserProfileResponse: {
            /** Format: uuid */
            id: string;
            userName: string;
            email: string;
        };
        GetUserResponse: {
            /** Format: uuid */
            userId: string;
            username: string;
        };
        HttpResult: {
            isSuccess?: boolean;
            isFailure?: boolean;
            errorMessage?: string;
            /** Format: int32 */
            statusCode?: number | string;
        };
        HttpResultOfConversationDetailsResponse: {
            value?: components["schemas"]["ConversationDetailsResponse"];
            isSuccess?: boolean;
            isFailure?: boolean;
            errorMessage?: string;
            /** Format: int32 */
            statusCode?: number | string;
        };
        HttpResultOfGetUserProfileResponse: {
            value?: components["schemas"]["GetUserProfileResponse"];
            isSuccess?: boolean;
            isFailure?: boolean;
            errorMessage?: string;
            /** Format: int32 */
            statusCode?: number | string;
        };
        HttpResultOfGuid: {
            /** Format: uuid */
            value?: string;
            isSuccess?: boolean;
            isFailure?: boolean;
            errorMessage?: string;
            /** Format: int32 */
            statusCode?: number | string;
        };
        HttpResultOfIEnumerableOfChatMessageResponse: {
            value?: null | components["schemas"]["ChatMessageResponse"][];
            isSuccess?: boolean;
            isFailure?: boolean;
            errorMessage?: string;
            /** Format: int32 */
            statusCode?: number | string;
        };
        HttpResultOfIEnumerableOfGetUserResponse: {
            value?: null | components["schemas"]["GetUserResponse"][];
            isSuccess?: boolean;
            isFailure?: boolean;
            errorMessage?: string;
            /** Format: int32 */
            statusCode?: number | string;
        };
        HttpResultOfIEnumerableOfUserConversationResponse: {
            value?: null | components["schemas"]["UserConversationResponse"][];
            isSuccess?: boolean;
            isFailure?: boolean;
            errorMessage?: string;
            /** Format: int32 */
            statusCode?: number | string;
        };
        LoginUserRequest: {
            email: string;
            password: string;
        };
        RegisterUserRequest: {
            username: string;
            email: string;
            password: string;
        };
        SendMessageRequest: {
            /** Format: uuid */
            conversationId: string;
            /** Format: uuid */
            receiverId: string;
            content: string;
        };
        UserConversationResponse: {
            /** Format: uuid */
            conversationId: string;
            /** Format: uuid */
            userId: string;
            username: string;
            lastMessage: string;
            /** Format: int32 */
            unReadMessage: number | string;
            /** Format: date-time */
            lastMessageTime: null | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
